### ISSUE TITLE
Animations CSS Loading

### ISSUE THREAD

**Issue by cosmin-serbanescu** [Codeinwp/gutenberg-animation#7]
@HardeepAsrani 
Probably it's best to load the animations CSS files only if there are elements on page that have animations set.
Currently the plugin is loading a 61KB file + a smaller one for this feature.
Plus it seems to be loaded even if we're not using Gutenberg on page but Elementor.

**Comment by HardeepAsrani** [comment]
We can but I'm not sure how we would go about it. The thing will be here to check if any block uses the "animate" class but that will require us to parse the blocks and check for the CSS, which might not be the most efficient solution.

What do you think @selul?

**Comment by selul** [comment]
indeed, it might be too overkill right now. 
we can just make sure when the plugin setting for animation is off, the css is not loaded, which we should already do

**Comment by HardeepAsrani** [comment]
Yup, we already do that. Closing it for now, if anyone can think of a solution then feel free to reopen.
